## Data Cleaning and Preprocessing:

In [2]:
import pandas as pd

### Handling Missing Data:

In [ ]:
data = pd.Series([11, None, 45, 78, None])

data.dropna()  # remove all entries (rows) where value is NaN
data.fillna(5)  # replace NaN with fixed value
data.fillna(data.mean())  # replace NaN with mean
data.fillna(data.min())  # replace NaN with minimum value
data.fillna(data.max())  # replace NaN with maximum value

0    11.0
1    78.0
2    45.0
3    78.0
4    78.0
dtype: float64

### Remove Duplicates:

In [33]:
s1 = pd.Series([1,2,1,4])
s2 = pd.Series([1,23,1,45])

data_1 = pd.DataFrame({
    'C1': s1,
    'C2': s2
})

data_1.drop_duplicates() # removes rows where ALL column values are exactly the same

   C1  C2
0   1   1
1   2  23
3   4  45

### Replace Values:

In [47]:
data_1.replace(1, 233) # replace all occurrences of 1 with 233 (entire DataFrame, not row/column specific)

      C1   C2
0  233.0  233
1    2.0   23
2  233.0  233
3    4.0   45

In [46]:
data_1['C1'] = data_1['C1'].astype(float)  # convert C1 column data type to float
data_1

    C1  C2
0  1.0   1
1  2.0  23
2  1.0   1
3  4.0  45

### String Operations:

In [50]:
data_1['C3'] = ['yes', 'no', 'or', 'and']  # create new column C3 with string values
# data_1['C3'].str.lower()  # convert all strings in C3 to lowercase
data_1['C3'].str.upper()  # convert all strings in C3 to uppercase (returns new Series)

0    YES
1     NO
2     OR
3    AND
Name: C3, dtype: str

## Data Aggregation and Grouping:

### GroupBy Example:

In [4]:
s1 = pd.Series(['A', 'B', 'A', 'B', 'C'])
s2 = pd.Series([11, 23, 53, 55, 34])

# Create DataFrame
data_2 = pd.DataFrame({
    'Name': s1,
    'lemonades': s2
})

# groupby('Name') groups rows having the same Name together
data_2.groupby('Name').sum()    # Sum of values
data_2.groupby('Name').mean()   # Average of values
data_2.groupby('Name').max()    # Highest value
data_2.groupby('Name').min()    # Lowest value

      lemonades
Name
A            11
B            23
C            34

### Pivot Tables:

In [19]:
# pivot_table() groups rows by 'Name' and summarizes the 'lemonades' numbers
# If a Name appears multiple times, its lemonade values are combined
# By default, pivot_table() calculates the average (mean) of those numbers

# By default mean
data_2.pivot_table(values='lemonades', index='Name')

# Sum of values
data_2.pivot_table(values='lemonades', index='Name', aggfunc='sum')

# Maximum value
data_2.pivot_table(values='lemonades', index='Name', aggfunc='max')

# Minimum value
data_2.pivot_table(values='lemonades', index='Name', aggfunc='min')

# Count how many values are in each group
data_2.pivot_table(values='lemonades', index='Name', aggfunc='count')

      lemonades
Name
A             2
B             2
C             1

### Crosstab:

In [30]:
# crosstab() counts how many times each combination of 'Name' and 'lemonades' appears
# Rows represent unique Names and columns represent lemonade values
# The numbers in the table show the frequency/count of occurrences

pd.crosstab(data_2['Name'], data_2['lemonades'])

lemonades  11  23  34  53  55
Name
A           1   0   0   1   0
B           0   1   0   0   1
C           0   0   1   0   0

## Merging, Joining and Concatinating:

### Concatinating:

In [23]:
s1 = pd.Series(['A', 'B', 'A', 'B', 'D'])
s2 = pd.Series([11, 22, 55, 66, 33])

data_3 = pd.DataFrame({
    'Name': s1,
    'lemon': s2
})

# concat() stacks DataFrames row-wise; matching columns are combined, non-matching columns are filled with NaN only where data is missing
pd.concat([data_2, data_3])

  Name  lemonades  lemon
0    A       11.0    NaN
1    B       23.0    NaN
2    A       53.0    NaN
3    B       55.0    NaN
4    C       34.0    NaN
0    A        NaN   11.0
1    B        NaN   22.0
2    A        NaN   55.0
3    B        NaN   66.0
4    D        NaN   33.0

### Merge:

In [24]:
# Merge data_2 and data_3 using "Name" as the key column
# Only rows with EXACT matching values in "Name" in BOTH DataFrames are kept
# If names are different or missing in either DataFrame, those rows are excluded (inner join behavior)
pd.merge(data_2, data_3, on='Name')

  Name  lemonades  lemon
0    A         11     11
1    A         11     55
2    B         23     22
3    B         23     66
4    A         53     11
5    A         53     55
6    B         55     22
7    B         55     66

### Join on Index:

In [28]:
# Join data_2 with data_3 by matching data_2["Name"] with data_3 index
# Default is LEFT join → keeps all rows from data_2, missing matches become NaN
# Unlike merge(), join uses index-based matching (after set_index) instead of column-to-column matching

data_2.join(data_3.set_index('Name'), on='Name')

  Name  lemonades  lemon
0    A         11   11.0
0    A         11   55.0
1    B         23   22.0
1    B         23   66.0
2    A         53   11.0
2    A         53   55.0
3    B         55   22.0
3    B         55   66.0
4    C         34    NaN