In [5]:
import pandas as pd
pd.__version__

'3.0.3'

## Key Data Structures (Series, DataFrame):
### 1. Pandas Series:

In [54]:
# Series ---> One List
sales = pd.Series([1,2,3,4,5])
print(sales[2]) # Indexing 
sales[1:4] # Slicing ---> data[start_ind:end_ind]
sales.index # Display the indexes of the Series --> OutPut ---> RangeIndex(start=0, stop=5, step=1)
sales.values   # Returns all values of the Series as a NumPy array
sales.dtype    # Returns the data type of the Series values


# Create a Series with custom index labels instead of default numbers
sales = pd.Series([10, 20, 30], index=['Mon', 'Tue', 'Wed'])
# sales = pd.Series([10, 20, 30], index=list('abc'))  # 'abc' is split into characters: ['a', 'b', 'c'] and used as custom index

# Display all custom indexes (row labels)
print(sales.index)

# Access the value using the custom index label 'Tue'
print(sales['Tue']) # Output will be 20

3
Index(['Mon', 'Tue', 'Wed'], dtype='str')
20

### Methods:

In [ ]:
series = pd.Series([8,7,3,2,5,6,1])
series.head(3)  # Returns first 3 elements (default = 5 if no value given)
series.tail(3)   # Returns last 3 elements (default = 5 if no value given)
series.sample(4)  # Returns 4 random elements from the Series/DataFrame (By default returns 1 random element)
series.sort_values()  # Sorts values in ascending order (small to large)
series.sort_values(ascending=False)  # Sorts values in descending order (large to small)
series.count() # Returns total number of non-missing (non-NaN) values
series.isnull() # Returns True for missing (NaN) values, False otherwise
series.notnull() # Returns True for non-missing (valid) values, False for NaN (missing) values

0    True
1    True
2    True
3    True
4    True
5    True
6    True
dtype: bool

### Operations:

In [ ]:
series + 1   # Adds 1 to each element in the Series
series * 2   # Multiplies each element by 2
series ** 2  # Squares each element (power of 2)
series / 2   # Divides each element by 2

0    4.0
1    3.5
2    1.5
3    1.0
4    2.5
5    3.0
6    0.5
dtype: float64

### Missing Values:

In [51]:
series_with_missing = pd.Series([1, None, 3, 6, None])  # Series with missing values (None = NaN)
series_with_missing.isnull()  # Returns True for missing values (NaN), False otherwise
series_with_missing.notnull()  # Returns True for valid values, False for NaN
series_with_missing.fillna(2)  # Temporarily fills NaN with 2 (does NOT change original Series)
series_with_missing  # # Original Series is shown again (still has NaN values)
series_with_missing = series_with_missing.fillna(2) # Replaces NaN values with 2 and creates a NEW Series, then updates the variable
series_with_missing  # Shows the updated Series (now NaN values are replaced with 2)

0    1.0
1    2.0
2    3.0
3    6.0
4    2.0
dtype: float64

### 2. Pandas DataFrame:

In [6]:
# DataFrame ---> Full Table
# DataFrame = table (rows + columns)
students = pd.DataFrame({
    "Name": ["Ali", "Ahmed", "Sara"],   # Name column
    "Age": [21, 22, 20],                # Age column
    "Marks": [85, 90, 88]               # Marks column
})

students

# Create DataFrame from collection of Series
s1= pd.Series([1,3,5,5,2,4])
s2= pd.Series([10,34,34,66,28,48])
s3= pd.Series([144,333,564,675,278,499])

data = pd.DataFrame({
    'C1': s1,
    'C2':s2
})

data

   C1  C2
0   1  10
1   3  34
2   5  34
3   5  66
4   2  28
5   4  48

### Attribute:

In [38]:
# Returns the shape of Series s1 (number of rows,)
s1.shape

# Returns the shape of DataFrame (rows, columns)
data.shape

# Returns column names of the DataFrame
data.columns

# Returns data types of each column
data.dtypes

# Returns total number of elements in the DataFrame
data.size


# Returns number of dimensions
data.ndim

2

### Accessing the Data:

In [96]:
# Create DataFrame with custom row labels
data_1 = pd.DataFrame({
    'C1': [1, 3, 5],
    'C2': [10, 30, 50]
}, index=['A', 'B', 'C'])

data_1

# Using labels (row label + column name)
# loc uses actual row/column labels
data_1.loc['B', 'C1']

# Using index positions (row number + column number)
# iloc uses integer index positions
data_1.iloc[1, 0]

np.int64(3)

### Methods:

In [54]:
# Displays first 5 rows
data.head()

# Displays last 5 rows
data.tail()

# Randomly returns 5 rows from the DataFrame
data.sample()

# Gives summary information about DataFrame
data.info()

# Statistical summary of numeric columns
data.describe()

# Number of rows and columns
len(data)

# Returns total non-null values
data.count()

# Returns unique values in a column
data['C1'].unique()

# Returns number of unique values
data['C1'].nunique()

# Returns maximum value
data['C1'].max()

# Returns minimum value
data['C1'].min()

# Returns mean value
data['C1'].mean()

# Returns sum of values
data['C1'].sum()

# Counts frequency of each unique value in the column
data['C1'].value_counts()

# Counts frequency including NULL/NaN values
data['C1'].value_counts(dropna=False)

# Sorts DataFrame rows based on values in column 'C1' in ascending order
data.sort_values('C1')

# Sort in descending order
data.sort_values('C1', ascending=False)

# Resets index back to default 0,1,2,... and removes old index
data.reset_index()

# Resets index to default 0,1,2,... and removes the old index completely (does not keep it as a column)
data.reset_index(drop=True)

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C1      6 non-null      int64
 1   C2      6 non-null      int64
dtypes: int64(2)
memory usage: 228.0 bytes

   C1  C2
0   1  10
1   3  34
2   5  34
3   5  66
4   2  28
5   4  48

### Filtering:

In [104]:
data[data['C1'] > 2]

   C1  C2
1   3  34
5   4  48

### Adding, Updating, Deleting:

In [105]:
# Add columns
data['Type'] = [1,2,3,4,5,6]   # add new column
data['Tips'] = [1,2,3,4,5,6]   # add new column

# Delete column
data = data.drop(columns='Tips')   # copy version (returns new df, original unchanged)
# data.drop(columns='Tips', inplace=True)  # inplace version (modifies original)
del data['Type']   # direct delete

# Update values
data.loc[data['C1'] == 2, 'C2'] = 8   # update specific rows
data.loc[data['C1'] > 4, ['C1','C2']] = 8   # update multiple columns same value
data.loc[data['C1'] > 4, ['C1','C2']] = [1, 8]   # update multiple columns different values
data

# Rename column
data.rename(columns={'C1': 'Column_1'})   # copy (original unchanged)
# data.rename(columns={'C1': 'Column_1'}, inplace=True)  # inplace (original changed)

   Column_1  C2
0         1  10
1         3  34
2         1   8
3         1   8
4         2   8
5         4  48

### Indexing and Selection:

In [ ]:
# Set Column as an Index
data.set_index('C1') # Srt column C1 as an custom index

    C2
C1
1   10
3   34
5   34
5   66
2   28
4   48

### MultiIndex Example:

In [ ]:
multi_data = pd.DataFrame({
    'Park': ['A', 'A', 'B', 'B'],
    'Name': ['Anna', 'Ben', 'Chris', 'Daisy'],
    'Lemonades': [2, 3, 4, 5]
}).set_index(['Park', 'Name'])  # create MultiIndex using Park and Name

multi_data

            Lemonades
Park Name
A    Anna           2
     Ben            3
B    Chris          4
     Daisy          5

### Selecting with Conditions:

In [ ]:
# Boolean indexing → best for dynamic/programmatic conditions
multi_data[multi_data['Lemonades'] > 2]  # filter rows where Lemonades > 2

            Lemonades
Park Name
A    Ben            3
B    Chris          4
     Daisy          5

### Query Method:

In [23]:
# Query method → cleaner for readable SQL-like filtering
multi_data.query('Lemonades > 2')

            Lemonades
Park Name
A    Ben            3
B    Chris          4
     Daisy          5

### Working with Data:

In [37]:
multi_data.to_csv('lemonades.csv') # Save the data into csv file
data = pd.read_csv('lemonades.csv') # Read the csv file
data

# create DataFrame from mixed data types (list, array, scalar)
import numpy as np

data = {
    'x': [1, 2, 3, 4],                 # list → 4 rows
    'y': np.array([20, 34, 54, 56]),  # array → length must match other columns
    'z': 40                            # scalar → repeated for every row
}

pd.DataFrame(data)  # all column lengths must match; scalar auto-broadcasts
# x and y must have the same length because each position represents one row.
# z is a single value (scalar), so Pandas automatically repeats it for all rows.

# create DataFrame from List
list = [[2, 3, 4, 3], [44, 2, 23, 4], [54, 24, 66, 35]]
pd.DataFrame(list, columns=['A', 'B', 'C', 'D'])

# Create DataFrame from Numpy array 
nparr = np.array([[21, 3, 44, 23], [4, 2, 4, 5], [34, 53, 27, 99]])
pd.DataFrame(nparr, columns=['W', 'X', 'Y', 'Z'])

    W   X   Y   Z
0  21   3  44  23
1   4   2   4   5
2  34  53  27  99